#pragma once

// Use UE_DISABLE_OPTIMIZATION for temporary development or UE_DISABLE_OPTIMIZATION_SHIP to submit
#define WL_DEBUG_BEGIN UE_DISABLE_OPTIMIZATION
#define WL_DEBUG_END UE_ENABLE_OPTIMIZATION
